export const TOOL_NAMES = {
  SEARCH_GITHUB_CODE: 'search_github_code',
  FETCH_GITHUB_FILE_CONTENT: 'fetch_github_file_content',
  VIEW_REPOSITORY: 'view_repository',
  NPM_VIEW: 'npm_view',
  SEARCH_GITHUB_REPOS: 'search_github_repos',
  SEARCH_GITHUB_COMMITS: 'search_github_commits',
  SEARCH_GITHUB_PULL_REQUESTS: 'search_github_pull_requests',
  GET_USER_ORGANIZATIONS: 'get_user_organizations',
  NPM_SEARCH: 'npm_search',
  VIEW_REPOSITORY_STRUCTURE: 'view_repository_structure',
  SEARCH_GITHUB_ISSUES: 'search_github_issues',
  SEARCH_GITHUB_DISCUSSIONS: 'search_github_discussions',
  SEARCH_GITHUB_TOPICS: 'search_github_topics',
  SEARCH_GITHUB_USERS: 'search_github_users',
  NPM_PACKAGE_STATS: 'npm_package_stats',
  NPM_DEPENDENCY_ANALYSIS: 'npm_dependency_analysis',
  GITHUB_ADVANCED_SEARCH: 'github_advanced_search',
} as const;

export const INDEX_MAP = {
  CRITICAL: '#CRITICAL#',
  SUCCESS: '#SUCCESS#',
  TARGET: '#TARGET#',
  WARNING: '#WARNING#',
  CODE: '#CODE#',
  PHASE1: '#PHASE1#',
  PHASE2: '#PHASE2#',
  PHASE3: '#PHASE3#',
  PHASE4: '#PHASE4#',
  IDEAL: '#IDEAL#',
  GOOD: '#GOOD#',
  BROAD: '#BROAD#',
  EXCESSIVE: '#EXCESSIVE#',
  DISCOVERY: '#DISCOVERY#',
  EXTRACTION: '#EXTRACTION#',
  VALIDATION: '#VALIDATION#',
  RECOVERY: '#RECOVERY#',
  BRANCH: '#BRANCH#',
  USER: '#USER#',
  CONDITIONAL: '#CONDITIONAL#',
  EFFICIENCY: '#EFFICIENCY#',
};
